application: you-ha-shock
version: 1
runtime: python
api_version: 1

handlers:
- url: .*/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)
  
- url: .*/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)
  expiration: "1s"
  
- url: .*/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*)
  
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  
- url: /admin/.*
  script: main.py
  login: admin

- url: /(cron|task)/.*
  script: task.py
  login: admin

- url: /api/.*
  script: api.py
  
- url: .*
  script: main.py
